# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
zonas = Spree::Zona.create([{ nombre: 'Zona 1'}, { nombre: 'Zona 2' }, { nombre: 'Zona 3' }, { nombre: 'Zona 4' }])
Spree::Diente.create(numero: '1.1', zona_id: '1' )
Spree::Diente.create(numero: '1.2', zona_id: '1' )
Spree::Diente.create(numero: '1.3', zona_id: '1' )
Spree::Diente.create(numero: '1.4', zona_id: '1' )
Spree::Diente.create(numero: '1.5', zona_id: '1' )
Spree::Diente.create(numero: '1.6', zona_id: '1' )
Spree::Diente.create(numero: '1.7', zona_id: '1' )
Spree::Diente.create(numero: '1.8', zona_id: '1' )
Spree::Diente.create(numero: '2.1', zona_id: '2' )
Spree::Diente.create(numero: '2.2', zona_id: '2' )
Spree::Diente.create(numero: '2.3', zona_id: '2' )
Spree::Diente.create(numero: '2.4', zona_id: '2' )
Spree::Diente.create(numero: '2.5', zona_id: '2' )
Spree::Diente.create(numero: '2.6', zona_id: '2' )
Spree::Diente.create(numero: '2.7', zona_id: '2' )
Spree::Diente.create(numero: '2.8', zona_id: '2' )
Spree::Diente.create(numero: '3.1', zona_id: '3' )
Spree::Diente.create(numero: '3.2', zona_id: '3' )
Spree::Diente.create(numero: '3.3', zona_id: '3' )
Spree::Diente.create(numero: '3.4', zona_id: '3' )
Spree::Diente.create(numero: '3.5', zona_id: '3' )
Spree::Diente.create(numero: '3.6', zona_id: '3' )
Spree::Diente.create(numero: '3.7', zona_id: '3' )
Spree::Diente.create(numero: '3.8', zona_id: '3' )
Spree::Diente.create(numero: '4.1', zona_id: '4' )
Spree::Diente.create(numero: '4.2', zona_id: '4' )
Spree::Diente.create(numero: '4.3', zona_id: '4' )
Spree::Diente.create(numero: '4.4', zona_id: '4' )
Spree::Diente.create(numero: '4.5', zona_id: '4' )
Spree::Diente.create(numero: '4.6', zona_id: '4' )
Spree::Diente.create(numero: '4.7', zona_id: '4' )
Spree::Diente.create(numero: '4.8', zona_id: '4' )
categories = Spree::Category.create([{ nombre: "Provisionales" }, { nombre: "Protesis Fija Unitaria" }, { nombre: "Implantes" }])
Spree::Trabajo.create(nombre: "Corona Provisoria sobre diente", category: categories.first )
Spree::Trabajo.create(nombre: "Corona Provisoria sobre pilar de implantes", category: categories.first )
Spree::Material.create(nombre: "PPMA", trabajo: Spree::Trabajo.first, price: '10', precio: '15000')

Spree::Core::Engine.load_seed if defined?(Spree::Core)
Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
